version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
    ports:
      - '8080:8080'
    volumes:
      - ./keycloak_data:/data
      - ./realm-export.json:/tmp/realm-export.json
